import React, { useEffect, useRef, useState } from 'react'
import { Button, Empty, Field, Panel } from '../ui.jsx'

const themes = [['morning', '潮汐圣域', '10:00–14:00'], ['afternoon', '赤色剧场', '14:00–20:00'], ['night', '深海回响', '其余时间']]

export default function Settings({ data, run, open, theme, previewTransparency }) {
  const [form, setForm] = useState({ ...data.settings })
  const [obsidian, setObsidian] = useState(null)
  const [backupId, setBackupId] = useState('')
  const [savedPath, setSavedPath] = useState('')
  const [restoreAccepted, setRestoreAccepted] = useState(false)
  const configKey = JSON.stringify(Object.fromEntries(Object.entries(data.settings).filter(([key]) => !['updated_at', 'created_at', 'workbuddy_last_sync'].includes(key))))
  const savedSettings = useRef(data.settings)
  const transparencyTimer = useRef(null)
  useEffect(() => {
    const previous = savedSettings.current
    savedSettings.current = data.settings
    setForm(current => Object.fromEntries(Object.keys({ ...current, ...data.settings }).map(key => [key, data.settings[key] !== previous[key] ? data.settings[key] : current[key]])))
  }, [configKey])
  useEffect(() => () => { clearTimeout(transparencyTimer.current); previewTransparency(null) }, [previewTransparency])
  useEffect(() => { fetch('/api/obsidian/recent').then(response => response.json()).then(setObsidian).catch(() => setObsidian(null)) }, [data.settings.obsidian_vault])
  const update = (key, value) => setForm(previous => ({ ...previous, [key]: value }))
  const agents = data.runtime?.agents || []
  const saveAppearance = patch => { setForm(previous => ({ ...previous, ...patch })); return run('save_settings', patch, { quiet: true }) }
  const changeTransparency = value => {
    update('theme_transparency', value)
    previewTransparency(value)
    clearTimeout(transparencyTimer.current)
    transparencyTimer.current = setTimeout(() => run('save_settings', { theme_transparency: value }, { quiet: true }), 300)
  }
  return <div className="page settings-page"><div className="settings-grid">
    <Panel title="外观主题" className="appearance-panel"><div className="skin-banner"><div className="skin-avatar">✧</div><div><strong>当前个性化主题：浊心斯卡蒂</strong><p>角色主题和称呼可以根据个人偏好配置，Personal OS 的工作流程保持一致。</p></div></div>
      <Field label="我的称呼（可选）"><input value={form.nickname || ''} onChange={event => update('nickname', event.target.value)} placeholder="例如：博士" /></Field>
      <label className="switch-row"><span><strong>自动随时间切换主题</strong><small>按照晨间、午后、夜间时段选择视觉主题。</small></span><input type="checkbox" checked={form.theme_mode === 'auto'} onChange={event => saveAppearance({ theme_mode: event.target.checked ? 'auto' : 'manual' })} /></label>
      <div className="theme-options">{themes.map(([key, name, hours]) => <button key={key} className={`theme-option ${theme === key ? 'selected' : ''}`} onClick={() => saveAppearance({ theme_mode: 'manual', manual_theme: key })}><span className={`theme-preview ${key}`} /><strong>{name}</strong><small>{hours}</small></button>)}</div>
      <Field label={`界面背景透明度 · ${form.theme_transparency ?? 8}%`}><input className="transparency-slider" aria-label="界面背景透明度" type="range" min="0" max="100" step="1" value={form.theme_transparency ?? 8} onChange={event => changeTransparency(Number(event.target.value))} /></Field><p className="muted">0% 为实色，100% 为全透明，三套主题共用。主题、自动切换和透明度改动后立即生效并保存。</p><div className="settings-actions"><Button variant="primary" onClick={() => run('save_settings', { nickname: form.nickname || '' })}>保存称呼</Button></div>
    </Panel>
    <div className="settings-side"><Panel title="个人规则（AI 参考）" action={<button className="text-link" onClick={() => open('rule')}>＋ 新建</button>}>{data.personal_rules.length ? data.personal_rules.map(rule => <div className="rule-row" key={rule.id}><span><strong>{rule.text}</strong><small>{rule.category}</small></span><Button onClick={() => open('rule-edit', rule)}>编辑</Button><input aria-label={`启用 ${rule.text}`} type="checkbox" checked={rule.enabled} onChange={event => run('update_rule', { id: rule.id, enabled: event.target.checked })} /></div>) : <Empty title="还没有个人规则" detail="通过可见、可修改的规则约束日报与建议。" />}<p className="muted">规则用于 AI 建议与执行上下文，人工完成和情报关键词筛选不会自动强制校验自然语言规则。</p></Panel>
      <Panel title="连接器与运行环境"><div className="integration-row"><span className="integration-icon">◈</span><div><strong>Obsidian</strong><small>{obsidian?.configured ? `已连接 · 最近 ${obsidian.files.length} 个文件` : '等待配置 vault 路径'}</small></div></div><Field label="Vault 路径"><input value={form.obsidian_vault || ''} onChange={event => update('obsidian_vault', event.target.value)} placeholder="/path/to/Obsidian" /></Field><Field label="代码仓库扫描目录（首页一键登记项目）"><input value={form.repo_scan_root ?? '~/My-Item'} onChange={event => update('repo_scan_root', event.target.value)} placeholder="~/My-Item" /></Field><div className="integration-row"><span className="integration-icon">◎</span><div><strong>Agent 命令行</strong><small>任务派给 Agent 时由 Personal OS 直接启动，任务内容和结果只存在本机。留空则在 PATH 中查找。</small></div></div>{agents.map(agent => <Field key={agent.id} label={`${agent.label} · ${agent.available ? '可用' : agent.remote ? '未启用' : '未找到'}`}><input value={form[agent.setting] || ''} onChange={event => update(agent.setting, event.target.value)} placeholder={agent.remote ? `${agent.binary} 命令路径，留空不启用` : agent.binary} /></Field>)}<div className="form-columns"><Field label="Multica 配置档（可选）"><input value={form.multica_profile || ''} onChange={event => update('multica_profile', event.target.value)} placeholder="default" /></Field><Field label="Multica 指派给的 Agent"><input value={form.multica_agent || ''} onChange={event => update('multica_agent', event.target.value)} placeholder="Multica 中的 Agent 名称" /></Field></div><div className="settings-actions"><Button onClick={() => run('save_settings', Object.fromEntries(['obsidian_vault', 'repo_scan_root', 'multica_profile', 'multica_agent', ...agents.map(agent => agent.setting)].map(key => [key, form[key] ?? ''])))}>保存连接器设置</Button></div></Panel>
      <Panel title="AI 日报来源"><p className="muted">直接阅读 WorkBuddy 已写入 Obsidian 的报告正文。按日期整理，打开工作台后每 30 秒检查更新，也可手动刷新。</p><Field label="日报目录（相对于 Vault）"><input value={form.daily_reports_folder ?? '每日AI'} onChange={event => update('daily_reports_folder', event.target.value)} placeholder="每日AI" /></Field><p className="muted">目录格式：每日AI / YYYY-MM-DD / 报告.md。当前发现 {data.daily_reports?.reports.length || 0} 篇，最新一期 {data.daily_reports?.latest_date || '暂无'}。</p>{data.daily_reports?.errors.map((error, index) => <p className="notice" key={index}>{error}</p>)}<Button onClick={() => run('save_settings', form)}>保存日报设置</Button></Panel>
      <Panel title="WorkBuddy 会话（可选）"><details><summary>会话同步设置</summary><p className="muted">只读同步本机用户消息和最终回复，进入情报与资料。保留来源，不自动完成任务，不读取推理/工具日志。已导入副本不跟随源删除。</p><Field label="WorkBuddy 数据目录"><input value={form.workbuddy_root || ''} onChange={event => update('workbuddy_root', event.target.value)} placeholder="~/.workbuddy" /></Field><Field label="导入此日期后更新的会话"><input type="date" max={data.today} value={form.workbuddy_since || ''} onChange={event => update('workbuddy_since', event.target.value)} /></Field><label><input type="checkbox" checked={!!form.workbuddy_enabled} onChange={event => update('workbuddy_enabled', event.target.checked)} />应用运行时每 5 分钟同步</label><div className="detail-actions wrap"><Button onClick={() => run('save_settings', form)}>保存连接设置</Button><Button disabled={!data.settings.workbuddy_root} onClick={() => run('sync_workbuddy', {})}>立即同步 WorkBuddy</Button></div>{data.settings.workbuddy_last_sync && <><p>最近同步：{new Date(data.settings.workbuddy_last_sync.at).toLocaleString()} · 新增 {data.settings.workbuddy_last_sync.added || 0} · 更新 {data.settings.workbuddy_last_sync.updated || 0} · 未变化 {data.settings.workbuddy_last_sync.unchanged || 0} · 错误 {data.settings.workbuddy_last_sync.error_count || 0}</p>{data.settings.workbuddy_last_sync.errors?.map((item, index) => <p className="notice" role="alert" key={index}>{item.error}</p>)}</>}<p className="muted">本地格式适配已针对 WorkBuddy 5.6 核验；版本变化会报告错误。默认最近 7 天，可调整日期；单次最多检查 1000 个会话。AI 日报从 Obsidian 独立读取，无需开启会话同步。</p></details></Panel>
      <Panel title="数据备份与恢复"><p className="muted">备份本地数据库；不包含项目文件或 Obsidian 笔记。恢复前自动另存当前数据。</p><Button onClick={async () => { const result = await run('create_backup', {}); if (result) setSavedPath(result.path) }}>创建备份</Button><Button onClick={async () => { const result = await run('export_data', {}); if (result) setSavedPath(result.path) }}>导出 JSON</Button>{savedPath && <Field label="已保存路径"><input readOnly value={savedPath} /></Field>}<Field label="选择备份"><select value={backupId} onChange={event => { setBackupId(event.target.value); setRestoreAccepted(false) }}><option value="">选择本机备份…</option>{data.backups?.map(item => <option key={item.id} value={item.id}>{item.id}</option>)}</select></Field><label><input type="checkbox" checked={restoreAccepted} onChange={event => setRestoreAccepted(event.target.checked)} />我确认用所选备份替换当前工作台数据</label><Button disabled={!backupId || !restoreAccepted} onClick={async () => { const result = await run('restore_backup', { id: backupId }); if (result) { setRestoreAccepted(false); setBackupId('') } }}>恢复所选备份</Button><p className="muted">自动化仅在应用运行时工作。关闭窗口会停止服务；错过的日报可以在历史页选择日期补记。</p></Panel>
    </div></div>
  </div>
}
